import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { ArrowRight, Award, Check, ChevronLeft, CircleHelp, Clock3, Flag, RotateCcw, Sparkles, X } from 'lucide-react';
import { officialQuestions } from './examQuestions';
import './styles.css';

const situationalQuestions = [
  { category: 'Principes & valeurs', question: 'Quelle est la devise de la République française ?', explanation: 'Cette réponse correspond précisément au sujet et au terme recherché dans la question. Pour cette question, la bonne réponse est « Liberté, Égalité, Fraternité ».', answer: 'Liberté, Égalité, Fraternité', choices: ['Liberté, Égalité, Fraternité', 'Unité, Travail, Progrès', 'Honneur, Patrie, Justice', 'Paix, Force, Solidarité'] },
  { category: 'Principes & valeurs', question: 'Que garantit la liberté d’expression ?', explanation: 'Cette réponse correspond à la règle juridique concernée : les droits sont protégés, mais leur exercice doit respecter la loi et les droits d’autrui. Pour cette question, la bonne réponse est « Le droit d’exprimer librement ses opinions dans le respect de la loi ».', answer: 'Le droit d’exprimer librement ses opinions dans le respect de la loi', choices: ['Le droit d’exprimer librement ses opinions dans le respect de la loi', 'Le droit de diffuser toute information sans aucune règle', 'Le droit de parler uniquement en privé', 'Le droit de remplacer une décision de justice'] },
  { category: 'Principes & valeurs', question: 'Que représente Marianne ?', explanation: 'La réponse donne la définition ou la fonction précise de la notion demandée, sans la confondre avec une notion voisine. Pour cette question, la bonne réponse est « La République française et ses valeurs ».', answer: 'La République française et ses valeurs', choices: ['La République française et ses valeurs', 'La monnaie européenne', 'La justice européenne', 'La fête nationale uniquement'] },
  { category: 'Principes & valeurs', question: 'En quelle année la loi de séparation des Églises et de l’État a-t-elle été votée ?', explanation: 'Cette date est le repère historique ou institutionnel précis demandé par la question. Pour cette question, la bonne réponse est « 1905 ».', answer: '1905', choices: ['1789', '1905', '1945', '1958'] },
  { category: 'Principes & valeurs', question: 'Quelle est la langue officielle de la République française ?', explanation: 'Cette réponse correspond précisément au sujet et au terme recherché dans la question. Pour cette question, la bonne réponse est « Le français ».', answer: 'Le français', choices: ['Le français', 'Le latin', 'L’anglais', 'Toutes les langues à égalité'] },
  { category: 'Principes & valeurs', question: 'Que signifie la laïcité ?', explanation: 'Cette réponse applique la liberté de conscience, l’égalité des citoyens et la neutralité de l’État prévues par le principe de laïcité. Pour cette question, la bonne réponse est « La séparation de l’État et des religions, avec la liberté de conscience ».', answer: 'La séparation de l’État et des religions, avec la liberté de conscience', choices: ['La séparation de l’État et des religions, avec la liberté de conscience', 'L’interdiction de toute religion', 'Le financement public de chaque religion', 'L’obligation de pratiquer une religion'] },
  { category: 'Institutions', question: 'Qui dirige l’action du Gouvernement ?', explanation: 'Cette réponse identifie l’autorité ou la mission compétente ; elle ne doit pas être confondue avec les fonctions des autres institutions. Pour cette question, la bonne réponse est « Le Premier ministre ».', answer: 'Le Premier ministre', choices: ['Le président du Sénat', 'Le Premier ministre', 'Le préfet', 'Le maire de Paris'] },
  { category: 'Institutions', question: 'De quoi le Parlement est-il composé ?', explanation: 'Cette réponse correspond précisément au sujet et au terme recherché dans la question. Pour cette question, la bonne réponse est « De l’Assemblée nationale et du Sénat ».', answer: 'De l’Assemblée nationale et du Sénat', choices: ['Du Gouvernement et du Conseil constitutionnel', 'De l’Assemblée nationale et du Sénat', 'Des maires et des préfets', 'De la Cour de cassation et du Sénat'] },
  { category: 'Institutions', question: 'Quel est le rôle du pouvoir législatif ?', explanation: 'Cette réponse identifie l’autorité ou la mission compétente ; elle ne doit pas être confondue avec les fonctions des autres institutions. Pour cette question, la bonne réponse est « Voter les lois ».', answer: 'Voter les lois', choices: ['Voter les lois', 'Rendre les décisions de justice', 'Diriger les communes', 'Commander la police municipale'] },
  { category: 'Institutions', question: 'Combien de députés composent l’Assemblée nationale ?', explanation: 'Cette réponse correspond précisément au sujet et au terme recherché dans la question. Pour cette question, la bonne réponse est « 577 ».', answer: '577', choices: ['348', '577', '620', '750'] },
  { category: 'Institutions', question: 'Quelle est la durée du mandat du maire et du conseil municipal ?', explanation: 'Cette réponse correspond précisément au sujet et au terme recherché dans la question. Pour cette question, la bonne réponse est « 6 ans ».', answer: '6 ans', choices: ['3 ans', '5 ans', '6 ans', '7 ans'] },
  { category: 'Institutions', question: 'Qui est le représentant de l’État dans le département ?', explanation: 'Cette réponse identifie l’autorité ou la mission compétente ; elle ne doit pas être confondue avec les fonctions des autres institutions. Pour cette question, la bonne réponse est « Le préfet ».', answer: 'Le préfet', choices: ['Le député', 'Le préfet', 'Le maire', 'Le président du conseil municipal'] },
  { category: 'Institutions', question: 'Quel est le régime politique de la France aujourd’hui ?', explanation: 'Cette réponse correspond précisément au sujet et au terme recherché dans la question. Pour cette question, la bonne réponse est « La Ve République ».', answer: 'La Ve République', choices: ['La Ire République', 'La IVe République', 'La Ve République', 'La monarchie constitutionnelle'] },
  { category: 'Droits & devoirs', question: 'La peine de mort en France est :', explanation: 'Cette réponse correspond à la règle juridique concernée : les droits sont protégés, mais leur exercice doit respecter la loi et les droits d’autrui. Pour cette question, la bonne réponse est « Abolie ».', answer: 'Abolie', choices: ['Obligatoire dans certains cas', 'Abolie', 'Réservée aux crimes politiques', 'Suspendue seulement en temps de paix'] },
  { category: 'Droits & devoirs', question: 'Quel droit permet de cesser le travail pour des revendications professionnelles ?', explanation: 'Cette réponse correspond à la règle juridique concernée : les droits sont protégés, mais leur exercice doit respecter la loi et les droits d’autrui. Pour cette question, la bonne réponse est « Le droit de grève ».', answer: 'Le droit de grève', choices: ['Le droit de grève', 'Le droit de propriété', 'Le droit de retrait électoral', 'Le droit de pétition uniquement'] },
  { category: 'Droits & devoirs', question: 'Quelle est la loi suprême du pays ?', explanation: 'Cette réponse correspond à la règle juridique concernée : les droits sont protégés, mais leur exercice doit respecter la loi et les droits d’autrui. Pour cette question, la bonne réponse est « La Constitution ».', answer: 'La Constitution', choices: ['Le Code de la route', 'La Constitution', 'Le règlement municipal', 'Le traité de Rome'] },
  { category: 'Droits & devoirs', question: 'Quelle liberté permet de croire ou de ne pas croire ?', explanation: 'Cette réponse correspond à la règle juridique concernée : les droits sont protégés, mais leur exercice doit respecter la loi et les droits d’autrui. Pour cette question, la bonne réponse est « La liberté de conscience ».', answer: 'La liberté de conscience', choices: ['La liberté de conscience', 'La liberté commerciale', 'La liberté syndicale', 'La liberté de circulation uniquement'] },
  { category: 'Droits & devoirs', question: 'Quelle proposition est une obligation pour les personnes résidant en France ?', explanation: 'Cette réponse correspond à la règle juridique concernée : les droits sont protégés, mais leur exercice doit respecter la loi et les droits d’autrui. Pour cette question, la bonne réponse est « Respecter les lois ».', answer: 'Respecter les lois', choices: ['Voter à chaque élection', 'Respecter les lois', 'Adhérer à une association', 'Posséder un logement'] },
  { category: 'Droits & devoirs', question: 'Pour quel motif la liberté d’expression peut-elle être limitée ?', explanation: 'Cette réponse correspond à la règle juridique concernée : les droits sont protégés, mais leur exercice doit respecter la loi et les droits d’autrui. Pour cette question, la bonne réponse est « En cas d’injure, de diffamation ou d’incitation à la haine ».', answer: 'En cas d’injure, de diffamation ou d’incitation à la haine', choices: ['En cas d’injure, de diffamation ou d’incitation à la haine', 'Lorsqu’une opinion est minoritaire', 'Lorsqu’une personne critique le Gouvernement', 'Pour interdire toute discussion politique'] },
  { category: 'Droits & devoirs', question: 'Que doit faire une victime de violences ?', explanation: 'Cette réponse correspond précisément au sujet et au terme recherché dans la question. Pour cette question, la bonne réponse est « Porter plainte auprès de la police ou de la gendarmerie ».', answer: 'Porter plainte auprès de la police ou de la gendarmerie', choices: ['Garder le silence dans tous les cas', 'Porter plainte auprès de la police ou de la gendarmerie', 'Quitter immédiatement le territoire', 'Attendre une autorisation de la mairie'] },
  { category: 'Histoire & culture', question: 'Quel était le surnom de Louis XIV ?', explanation: 'Cette réponse correspond précisément au sujet et au terme recherché dans la question. Pour cette question, la bonne réponse est « Le Roi-Soleil ».', answer: 'Le Roi-Soleil', choices: ['Le Roi-Soleil', 'Le Roi-Citoyen', 'Le Père de la Nation', 'Le Roi des Montagnes'] },
  { category: 'Histoire & culture', question: 'En quelle année Napoléon Ier est-il devenu empereur ?', explanation: 'Cette date est le repère historique ou institutionnel précis demandé par la question. Pour cette question, la bonne réponse est « 1804 ».', answer: '1804', choices: ['1789', '1792', '1804', '1815'] },
  { category: 'Histoire & culture', question: 'Qui était une figure de la Résistance française ?', explanation: 'Cette réponse correspond précisément au sujet et au terme recherché dans la question. Pour cette question, la bonne réponse est « Jean Moulin ».', answer: 'Jean Moulin', choices: ['Jean Moulin', 'Louis XIV', 'Jules Ferry', 'Georges Clemenceau'] },
  { category: 'Histoire & culture', question: 'En 1944, quel droit les femmes françaises ont-elles obtenu ?', explanation: 'Cette réponse correspond à la règle juridique concernée : les droits sont protégés, mais leur exercice doit respecter la loi et les droits d’autrui. Pour cette question, la bonne réponse est « Le droit de vote ».', answer: 'Le droit de vote', choices: ['Le droit de vote', 'Le droit de conduire', 'Le droit à la retraite', 'Le droit de grève'] },
  { category: 'Histoire & culture', question: 'Quelle organisation internationale a été créée en 1945 ?', explanation: 'Cette réponse correspond précisément au sujet et au terme recherché dans la question. Pour cette question, la bonne réponse est « L’ONU ».', answer: 'L’ONU', choices: ['L’ONU', 'L’OTAN', 'La BCE', 'La CECA'] },
  { category: 'Histoire & culture', question: 'Quel fleuve traverse Paris ?', explanation: 'Ce nom est le repère géographique ou territorial exact demandé par la question. Pour cette question, la bonne réponse est « La Seine ».', answer: 'La Seine', choices: ['La Loire', 'La Seine', 'Le Rhône', 'La Garonne'] },
  { category: 'Histoire & culture', question: 'Quelle chaîne de montagnes se situe entre la France et l’Espagne ?', explanation: 'Ce nom est le repère géographique ou territorial exact demandé par la question. Pour cette question, la bonne réponse est « Les Pyrénées ».', answer: 'Les Pyrénées', choices: ['Les Alpes', 'Les Vosges', 'Les Pyrénées', 'Le Jura'] },
  { category: 'Histoire & culture', question: 'Quelle cathédrale a été partiellement détruite par un incendie en 2019 ?', explanation: 'Cette réponse correspond précisément au sujet et au terme recherché dans la question. Pour cette question, la bonne réponse est « Notre-Dame de Paris ».', answer: 'Notre-Dame de Paris', choices: ['Notre-Dame de Paris', 'La cathédrale de Reims', 'La cathédrale de Chartres', 'La cathédrale de Strasbourg'] },
  { category: 'Histoire & culture', question: 'Quelle fête est la fête nationale française ?', explanation: 'Cette réponse correspond précisément au sujet et au terme recherché dans la question. Pour cette question, la bonne réponse est « Le 14 juillet ».', answer: 'Le 14 juillet', choices: ['Le 1er mai', 'Le 8 mai', 'Le 14 juillet', 'Le 11 novembre'] },
  { category: 'Institutions', question: 'Quelle est la devise de l’Union européenne ?', explanation: 'Cette réponse correspond précisément au sujet et au terme recherché dans la question. Pour cette question, la bonne réponse est « Unie dans la diversité ».', answer: 'Unie dans la diversité', choices: ['Unie dans la diversité', 'Liberté, Égalité, Fraternité', 'L’Europe pour tous', 'Ensemble vers la paix'] },
  { category: 'Institutions', question: 'Combien d’étoiles figurent sur le drapeau européen ?', explanation: 'Cette réponse correspond précisément au sujet et au terme recherché dans la question. Pour cette question, la bonne réponse est « 12 ».', answer: '12', choices: ['6', '10', '12', '27'] },
  { category: 'Institutions', question: 'En quelle année le traité de Maastricht a-t-il été signé ?', explanation: 'Cette date est le repère historique ou institutionnel précis demandé par la question. Pour cette question, la bonne réponse est « 1992 ».', answer: '1992', choices: ['1951', '1957', '1992', '2002'] },
  { category: 'Institutions', question: 'Où siège le Parlement européen ?', explanation: 'Ce nom est le repère géographique ou territorial exact demandé par la question. Pour cette question, la bonne réponse est « À Strasbourg ».', answer: 'À Strasbourg', choices: ['À Paris', 'À Strasbourg', 'À Genève', 'À Rome'] },
  { category: 'Institutions', question: 'Quel État a quitté l’Union européenne en 2020 ?', explanation: 'Cette réponse correspond précisément au sujet et au terme recherché dans la question. Pour cette question, la bonne réponse est « Le Royaume-Uni ».', answer: 'Le Royaume-Uni', choices: ['La Norvège', 'La Suisse', 'Le Royaume-Uni', 'L’Islande'] },
  { category: 'Vie quotidienne', question: 'Quel mariage est reconnu par l’État ?', explanation: 'Cette réponse indique le service, la démarche ou la règle applicable dans la vie quotidienne. Pour cette question, la bonne réponse est « Le mariage civil célébré à la mairie ».', answer: 'Le mariage civil célébré à la mairie', choices: ['Le mariage civil célébré à la mairie', 'Uniquement le mariage religieux', 'Une cérémonie familiale sans acte', 'Un mariage célébré par un employeur'] },
  { category: 'Vie quotidienne', question: 'À quel âge commence l’instruction obligatoire ?', explanation: 'Cette réponse correspond précisément au sujet et au terme recherché dans la question. Pour cette question, la bonne réponse est « 3 ans ».', answer: '3 ans', choices: ['3 ans', '5 ans', '6 ans', '16 ans'] },
  { category: 'Vie quotidienne', question: 'Quel numéro permet d’appeler la police ?', explanation: 'Cette réponse indique le service, la démarche ou la règle applicable dans la vie quotidienne. Pour cette question, la bonne réponse est « 17 ».', answer: '17', choices: ['15', '17', '18', '116 117'] },
  { category: 'Vie quotidienne', question: 'Où faut-il déclarer la naissance d’un enfant ?', explanation: 'Ce nom est le repère géographique ou territorial exact demandé par la question. Pour cette question, la bonne réponse est « À la mairie du lieu de naissance ».', answer: 'À la mairie du lieu de naissance', choices: ['À la préfecture uniquement', 'À la mairie du lieu de naissance', 'À l’école', 'À la caisse d’allocations familiales'] },
  { category: 'Vie quotidienne', question: 'Quelle aide permet d’avoir un avocat quand on a peu de ressources ?', explanation: 'Cette réponse correspond précisément au sujet et au terme recherché dans la question. Pour cette question, la bonne réponse est « L’aide juridictionnelle ».', answer: 'L’aide juridictionnelle', choices: ['L’aide juridictionnelle', 'La prime d’activité', 'La carte vitale', 'Le congé parental'] },
  { category: 'Vie quotidienne', question: 'Que protège le secret médical ?', explanation: 'Cette réponse correspond précisément au sujet et au terme recherché dans la question. Pour cette question, la bonne réponse est « La confidentialité des informations de santé ».', answer: 'La confidentialité des informations de santé', choices: ['La confidentialité des informations de santé', 'La gratuité de tous les soins', 'Le droit de choisir son médecin à l’étranger', 'L’absence de dossier médical'] },
  { category: 'Vie quotidienne', situation: true, question: 'Votre enfant est malade et ne peut pas aller à l’école. Que faites-vous ?', explanation: 'La réponse applique les règles qui protègent l’enfant, assurent la continuité de sa scolarité et organisent les échanges avec l’établissement. Pour cette question, la bonne réponse est « Prévenir l’école le jour même et justifier son absence ».', answer: 'Prévenir l’école le jour même et justifier son absence', choices: ['Prévenir l’école le jour même et justifier son absence', 'Ne rien signaler si l’absence dure moins d’une semaine', 'Demander à un voisin de prévenir la mairie', 'Attendre le retour des vacances scolaires'] },
  { category: 'Vie quotidienne', situation: true, question: 'Un voisin fait beaucoup de bruit à 2 heures du matin. Quelle est la meilleure réaction ?', explanation: 'La bonne conduite consiste à rechercher une solution amiable et à respecter la tranquillité, les droits et la sécurité des autres. Pour cette question, la bonne réponse est « Lui parler calmement, puis appeler la police si le trouble persiste ».', answer: 'Lui parler calmement, puis appeler la police si le trouble persiste', choices: ['Lui parler calmement, puis appeler la police si le trouble persiste', 'Couper son électricité soi-même', 'Répondre en faisant davantage de bruit', 'Publier son adresse sur les réseaux sociaux'] },
  { category: 'Vie quotidienne', situation: true, question: 'Où déposer un ancien réfrigérateur ?', explanation: 'Cette réponse respecte les règles de collecte et de protection de l’environnement applicables aux déchets concernés. Pour cette question, la bonne réponse est « À la déchetterie ou lors d’une collecte d’encombrants ».', answer: 'À la déchetterie ou lors d’une collecte d’encombrants', choices: ['À la déchetterie ou lors d’une collecte d’encombrants', 'Sur le trottoir sans autorisation', 'Dans une poubelle classique', 'Dans le hall de l’immeuble'] },
  { category: 'Droits & devoirs', situation: true, question: 'Vous êtes témoin d’un grave accident de voiture. Que faites-vous en premier ?', explanation: 'La priorité est de protéger les personnes, d’éviter d’aggraver le danger et d’alerter immédiatement les services de secours compétents. Pour cette question, la bonne réponse est « Sécuriser les lieux puis appeler les secours ».', answer: 'Sécuriser les lieux puis appeler les secours', choices: ['Sécuriser les lieux puis appeler les secours', 'Déplacer immédiatement toutes les victimes', 'Filmer la scène et la publier', 'Quitter les lieux sans prévenir personne'] },
  { category: 'Droits & devoirs', situation: true, question: 'Vous entendez des appels à l’aide chez un voisin. Quelle attitude adopter ?', explanation: 'La priorité est de protéger les personnes, d’éviter d’aggraver le danger et d’alerter immédiatement les services de secours compétents. Pour cette question, la bonne réponse est « Appeler immédiatement la police au 17 ».', answer: 'Appeler immédiatement la police au 17', choices: ['Appeler immédiatement la police au 17', 'Attendre plusieurs jours pour vérifier', 'Entrer par effraction', 'Mettre la musique plus fort'] },
  { category: 'Droits & devoirs', situation: true, question: 'Vous suspectez une fuite de gaz dans votre immeuble. Que devez-vous faire ?', explanation: 'La priorité est de protéger les personnes, d’éviter d’aggraver le danger et d’alerter immédiatement les services de secours compétents. Pour cette question, la bonne réponse est « Ne pas allumer de lumière, sortir et appeler les secours ».', answer: 'Ne pas allumer de lumière, sortir et appeler les secours', choices: ['Ne pas allumer de lumière, sortir et appeler les secours', 'Allumer une bougie pour chercher la fuite', 'Actionner tous les interrupteurs', 'Rester dans l’appartement et attendre'] },
  { category: 'Principes & valeurs', situation: true, question: 'Vous êtes agent d’une mairie. Pouvez-vous porter un signe religieux visible au travail ?', explanation: 'La réponse distingue la liberté de l’usager de l’obligation de neutralité qui s’impose aux agents publics, dans le respect de la loi et de l’ordre public. Pour cette question, la bonne réponse est « Non, les agents publics sont soumis à la neutralité religieuse ».', answer: 'Non, les agents publics sont soumis à la neutralité religieuse', choices: ['Non, les agents publics sont soumis à la neutralité religieuse', 'Oui, car aucune règle ne s’applique aux agents', 'Oui, uniquement le vendredi', 'Seulement si les usagers sont d’accord'] },
  { category: 'Principes & valeurs', situation: true, question: 'Vous êtes usager d’une préfecture et portez un signe religieux. Est-ce autorisé ?', explanation: 'La réponse distingue la liberté de l’usager de l’obligation de neutralité qui s’impose aux agents publics, dans le respect de la loi et de l’ordre public. Pour cette question, la bonne réponse est « Oui, tant que vous respectez la loi et l’ordre public ».', answer: 'Oui, tant que vous respectez la loi et l’ordre public', choices: ['Oui, tant que vous respectez la loi et l’ordre public', 'Non, tout signe religieux est interdit aux usagers', 'Seulement avec une autorisation du préfet', 'Uniquement dans les bureaux privés'] },
  { category: 'Institutions', situation: true, question: 'La police vous demande vos papiers lors d’un contrôle d’identité. Que faites-vous ?', explanation: 'La démarche indiquée permet de coopérer avec les autorités et d’utiliser la procédure prévue par la loi, sans régler le problème par soi-même. Pour cette question, la bonne réponse est « Rester calme et présenter un document d’identité ».', answer: 'Rester calme et présenter un document d’identité', choices: ['Rester calme et présenter un document d’identité', 'Refuser systématiquement de répondre', 'Détruire ses papiers', 'Appeler son employeur pour décider'] },
  { category: 'Institutions', situation: true, question: 'Vous trouvez un portefeuille dans la rue. Que faites-vous ?', explanation: 'La réponse décrit le comportement attendu dans cette situation concrète, en respectant la loi, la sécurité et les droits d’autrui. Pour cette question, la bonne réponse est « Le déposer au commissariat ou au service des objets trouvés ».', answer: 'Le déposer au commissariat ou au service des objets trouvés', choices: ['Le déposer au commissariat ou au service des objets trouvés', 'Garder l’argent et jeter les papiers', 'Le laisser sur la chaussée', 'Le vendre sur internet'] },
  { category: 'Droits & devoirs', situation: true, question: 'Un restaurant refuse une personne en fauteuil roulant parce que cela gênerait le service. Que dit la loi ?', explanation: 'La réponse décrit le comportement attendu dans cette situation concrète, en respectant la loi, la sécurité et les droits d’autrui. Pour cette question, la bonne réponse est « C’est une discrimination interdite ».', answer: 'C’est une discrimination interdite', choices: ['C’est une discrimination interdite', 'C’est toujours au client de trouver une solution', 'C’est autorisé si le restaurant est occupé', 'C’est uniquement un problème commercial'] },
  { category: 'Droits & devoirs', situation: true, question: 'Un employeur licencie un salarié parce qu’il a fait grève. Est-ce légal ?', explanation: 'La réponse décrit le comportement attendu dans cette situation concrète, en respectant la loi, la sécurité et les droits d’autrui. Pour cette question, la bonne réponse est « Non, le licenciement pour avoir exercé le droit de grève est illégal ».', answer: 'Non, le licenciement pour avoir exercé le droit de grève est illégal', choices: ['Non, le licenciement pour avoir exercé le droit de grève est illégal', 'Oui, la grève est interdite en France', 'Oui, si la grève dure plus d’une heure', 'Seulement si le salarié est majeur'] },
  { category: 'Vie quotidienne', situation: true, question: 'La cantine ne propose pas le plat correspondant à votre religion. Que pouvez-vous demander ?', explanation: 'La réponse distingue la liberté de l’usager de l’obligation de neutralité qui s’impose aux agents publics, dans le respect de la loi et de l’ordre public. Pour cette question, la bonne réponse est « Un menu sans viande ou végétarien s’il existe ».', answer: 'Un menu sans viande ou végétarien s’il existe', choices: ['Un menu sans viande ou végétarien s’il existe', 'Un menu confessionnel obligatoire', 'La fermeture de la cantine', 'Une dispense permanente de scolarité'] },
  { category: 'Vie quotidienne', situation: true, question: 'Vous n’êtes pas d’accord avec une punition donnée par l’enseignant. Que faites-vous ?', explanation: 'La réponse décrit le comportement attendu dans cette situation concrète, en respectant la loi, la sécurité et les droits d’autrui. Pour cette question, la bonne réponse est « Demander un rendez-vous avec l’enseignant ou le directeur ».', answer: 'Demander un rendez-vous avec l’enseignant ou le directeur', choices: ['Demander un rendez-vous avec l’enseignant ou le directeur', 'Menacer l’enseignant', 'Refuser toute future scolarisation', 'Saisir directement le Parlement'] },
  { category: 'Vie quotidienne', situation: true, question: 'Vous souhaitez inscrire votre enfant de 3 ans à l’école. Que prévoit la loi ?', explanation: 'La réponse applique les règles qui protègent l’enfant, assurent la continuité de sa scolarité et organisent les échanges avec l’établissement. Pour cette question, la bonne réponse est « L’instruction est obligatoire dès 3 ans ».', answer: 'L’instruction est obligatoire dès 3 ans', choices: ['L’instruction est obligatoire dès 3 ans', 'L’école ne commence qu’à 6 ans', 'L’inscription dépend du lieu de travail des parents', 'L’enfant doit attendre le collège'] },
  { category: 'Vie quotidienne', situation: true, question: 'Vous organisez une fête chez vous. Quelle précaution prendre ?', explanation: 'La bonne conduite consiste à rechercher une solution amiable et à respecter la tranquillité, les droits et la sécurité des autres. Pour cette question, la bonne réponse est « Prévenir les voisins et réduire le bruit le soir ».', answer: 'Prévenir les voisins et réduire le bruit le soir', choices: ['Prévenir les voisins et réduire le bruit le soir', 'Ne prévenir personne et augmenter la musique', 'Bloquer l’accès à l’immeuble', 'Obliger les voisins à participer'] },
  { category: 'Vie quotidienne', situation: true, question: 'Un conflit vous oppose à votre voisin sur la limite du jardin. Que faire ?', explanation: 'La bonne conduite consiste à rechercher une solution amiable et à respecter la tranquillité, les droits et la sécurité des autres. Pour cette question, la bonne réponse est « Chercher un accord amiable ou un médiateur ».', answer: 'Chercher un accord amiable ou un médiateur', choices: ['Chercher un accord amiable ou un médiateur', 'Modifier la clôture pendant la nuit', 'Menacer le voisin', 'Appeler les secours pour trancher'] },
  { category: 'Vie quotidienne', situation: true, question: 'Le pharmacien propose un médicament générique. Quelle réponse est adaptée ?', explanation: 'La réponse décrit le comportement attendu dans cette situation concrète, en respectant la loi, la sécurité et les droits d’autrui. Pour cette question, la bonne réponse est « L’accepter : il contient la même molécule active ».', answer: 'L’accepter : il contient la même molécule active', choices: ['L’accepter : il contient la même molécule active', 'Le refuser car il est toujours inefficace', 'Le donner à un voisin', 'Le prendre sans lire la prescription'] },
  { category: 'Vie quotidienne', situation: true, question: 'Vous devez vous arrêter de travailler pour vous occuper d’un enfant. Qui peut demander un congé parental ?', explanation: 'La réponse applique les règles qui protègent l’enfant, assurent la continuité de sa scolarité et organisent les échanges avec l’établissement. Pour cette question, la bonne réponse est « La mère ou le père ».', answer: 'La mère ou le père', choices: ['La mère ou le père', 'Uniquement le grand-parent', 'Uniquement l’employeur', 'Personne dans cette situation'] },
  { category: 'Vie quotidienne', situation: true, question: 'Vous déménagez dans une autre ville. Quelle démarche est importante ?', explanation: 'La réponse décrit le comportement attendu dans cette situation concrète, en respectant la loi, la sécurité et les droits d’autrui. Pour cette question, la bonne réponse est « Mettre à jour votre adresse auprès des organismes concernés ».', answer: 'Mettre à jour votre adresse auprès des organismes concernés', choices: ['Mettre à jour votre adresse auprès des organismes concernés', 'Ne prévenir personne pendant dix ans', 'Changer uniquement votre numéro de téléphone', 'Prévenir seulement vos voisins'] },
  { category: 'Droits & devoirs', situation: true, question: 'Un ami veut conduire après avoir beaucoup bu. Que faites-vous ?', explanation: 'La réponse décrit le comportement attendu dans cette situation concrète, en respectant la loi, la sécurité et les droits d’autrui. Pour cette question, la bonne réponse est « L’empêcher de conduire et proposer une autre solution ».', answer: 'L’empêcher de conduire et proposer une autre solution', choices: ['L’empêcher de conduire et proposer une autre solution', 'L’encourager à rouler lentement', 'Lui prêter votre voiture', 'Ignorer la situation'] },
  { category: 'Droits & devoirs', situation: true, question: 'Vous voyez une personne âgée debout dans les transports. Quelle attitude est civique ?', explanation: 'La réponse décrit le comportement attendu dans cette situation concrète, en respectant la loi, la sécurité et les droits d’autrui. Pour cette question, la bonne réponse est « Lui céder votre place ».', answer: 'Lui céder votre place', choices: ['Lui céder votre place', 'Lui demander de descendre', 'Faire semblant de dormir', 'Réserver plusieurs places'] },
  { category: 'Droits & devoirs', situation: true, question: 'Vous jetez un emballage par la fenêtre de votre voiture. Que risquez-vous ?', explanation: 'La réponse décrit le comportement attendu dans cette situation concrète, en respectant la loi, la sécurité et les droits d’autrui. Pour cette question, la bonne réponse est « Une amende pour abandon de déchets ».', answer: 'Une amende pour abandon de déchets', choices: ['Une amende pour abandon de déchets', 'Aucune conséquence', 'Une récompense citoyenne', 'Un permis de conduire automatique'] },
  { category: 'Droits & devoirs', situation: true, question: 'Vous ne comprenez pas les consignes de tri. Que devez-vous faire ?', explanation: 'Cette réponse respecte les règles de collecte et de protection de l’environnement applicables aux déchets concernés. Pour cette question, la bonne réponse est « Trier les déchets dans les poubelles adaptées ».', answer: 'Trier les déchets dans les poubelles adaptées', choices: ['Trier les déchets dans les poubelles adaptées', 'Tout mettre dans la poubelle classique', 'Déposer les déchets dans la rue', 'Les brûler dans le jardin'] },
  { category: 'Principes & valeurs', situation: true, question: 'Une personne se moque publiquement d’une religion. Dans quel cas cela peut-il être puni ?', explanation: 'La réponse distingue la liberté de l’usager de l’obligation de neutralité qui s’impose aux agents publics, dans le respect de la loi et de l’ordre public. Pour cette question, la bonne réponse est « Si elle appelle à la haine ou à la violence contre des croyants ».', answer: 'Si elle appelle à la haine ou à la violence contre des croyants', choices: ['Si elle appelle à la haine ou à la violence contre des croyants', 'Dès qu’une opinion déplaît', 'Dès qu’elle parle de religion', 'Jamais, même en cas de menace'] },
  { category: 'Principes & valeurs', situation: true, question: 'Un proche menace une personne qui change de religion. Que faut-il retenir ?', explanation: 'La réponse distingue la liberté de l’usager de l’obligation de neutralité qui s’impose aux agents publics, dans le respect de la loi et de l’ordre public. Pour cette question, la bonne réponse est « Changer de religion est libre et les menaces sont punissables ».', answer: 'Changer de religion est libre et les menaces sont punissables', choices: ['Changer de religion est libre et les menaces sont punissables', 'La famille décide de la religion', 'Changer de religion est interdit', 'Les menaces sont autorisées en privé'] },
  { category: 'Principes & valeurs', situation: true, question: 'Lors d’une manifestation autorisée, la police demande de se disperser. Que faites-vous ?', explanation: 'La démarche indiquée permet de coopérer avec les autorités et d’utiliser la procédure prévue par la loi, sans régler le problème par soi-même. Pour cette question, la bonne réponse est « Obéir à la demande de dispersion ».', answer: 'Obéir à la demande de dispersion', choices: ['Obéir à la demande de dispersion', 'Rester par provocation', 'Empêcher les policiers de travailler', 'Jeter des objets'] },
  { category: 'Principes & valeurs', situation: true, question: 'Un agent immobilier refuse une visite à cause de votre couleur de peau. Quel recours est possible ?', explanation: 'La réponse décrit le comportement attendu dans cette situation concrète, en respectant la loi, la sécurité et les droits d’autrui. Pour cette question, la bonne réponse est « Saisir le Défenseur des droits et porter plainte ».', answer: 'Saisir le Défenseur des droits et porter plainte', choices: ['Saisir le Défenseur des droits et porter plainte', 'Accepter car c’est son choix', 'Menacer l’agent', 'Changer de nationalité'] },
  { category: 'Principes & valeurs', situation: true, question: 'Vous êtes témoin d’une agression verbale homophobe. Que faites-vous ?', explanation: 'La réponse décrit le comportement attendu dans cette situation concrète, en respectant la loi, la sécurité et les droits d’autrui. Pour cette question, la bonne réponse est « Alerter la police et témoigner si nécessaire ».', answer: 'Alerter la police et témoigner si nécessaire', choices: ['Alerter la police et témoigner si nécessaire', 'Rire avec l’agresseur', 'Filmer sans jamais alerter', 'Demander à la victime de partir'] },
  { category: 'Principes & valeurs', situation: true, question: 'Une femme mariée veut ouvrir un compte bancaire seule. Est-ce possible ?', explanation: 'La réponse décrit le comportement attendu dans cette situation concrète, en respectant la loi, la sécurité et les droits d’autrui. Pour cette question, la bonne réponse est « Oui, elle peut ouvrir un compte sans l’autorisation de son époux ».', answer: 'Oui, elle peut ouvrir un compte sans l’autorisation de son époux', choices: ['Oui, elle peut ouvrir un compte sans l’autorisation de son époux', 'Non, son époux doit signer', 'Uniquement avec l’accord de la mairie', 'Uniquement après un divorce'] },
  { category: 'Principes & valeurs', situation: true, question: 'Une entreprise paie une femme moins qu’un homme à compétences égales. Que dit la loi ?', explanation: 'La réponse décrit le comportement attendu dans cette situation concrète, en respectant la loi, la sécurité et les droits d’autrui. Pour cette question, la bonne réponse est « À travail de valeur égale, le salaire doit être égal ».', answer: 'À travail de valeur égale, le salaire doit être égal', choices: ['À travail de valeur égale, le salaire doit être égal', 'L’employeur peut toujours le faire', 'La différence est obligatoire', 'Cela ne concerne que les fonctionnaires'] },
  { category: 'Institutions', situation: true, question: 'Vous recevez une amende, mais vous n’étiez pas le conducteur. Que faites-vous ?', explanation: 'La réponse décrit le comportement attendu dans cette situation concrète, en respectant la loi, la sécurité et les droits d’autrui. Pour cette question, la bonne réponse est « Contester en désignant la personne qui conduisait ».', answer: 'Contester en désignant la personne qui conduisait', choices: ['Contester en désignant la personne qui conduisait', 'Ignorer l’amende', 'La jeter immédiatement', 'Payer deux fois'] },
  { category: 'Institutions', situation: true, question: 'Vous manquez de ressources pour payer un avocat. Quelle aide demander ?', explanation: 'La réponse décrit le comportement attendu dans cette situation concrète, en respectant la loi, la sécurité et les droits d’autrui. Pour cette question, la bonne réponse est « L’aide juridictionnelle ».', answer: 'L’aide juridictionnelle', choices: ['L’aide juridictionnelle', 'Une autorisation de la police', 'Une carte de transport', 'Un permis de construire'] },
  { category: 'Institutions', situation: true, question: 'Vous devez remplir une déclaration de revenus mais vous n’avez aucun revenu. Que faire ?', explanation: 'La réponse décrit le comportement attendu dans cette situation concrète, en respectant la loi, la sécurité et les droits d’autrui. Pour cette question, la bonne réponse est « Déclarer tout de même ses revenus, même s’ils sont nuls ».', answer: 'Déclarer tout de même ses revenus, même s’ils sont nuls', choices: ['Déclarer tout de même ses revenus, même s’ils sont nuls', 'Ne jamais faire de déclaration', 'Déclarer uniquement à la mairie', 'Attendre d’avoir un emploi'] },
  { category: 'Institutions', situation: true, question: 'Votre employeur vous demande pour qui vous avez voté. Devez-vous répondre ?', explanation: 'La réponse décrit le comportement attendu dans cette situation concrète, en respectant la loi, la sécurité et les droits d’autrui. Pour cette question, la bonne réponse est « Non, le vote est personnel et secret ».', answer: 'Non, le vote est personnel et secret', choices: ['Non, le vote est personnel et secret', 'Oui, c’est obligatoire', 'Oui, si l’employeur insiste', 'Seulement par écrit'] },
  { category: 'Institutions', situation: true, question: 'Avec une carte de résident, pouvez-vous voter à l’élection présidentielle ?', explanation: 'La réponse décrit le comportement attendu dans cette situation concrète, en respectant la loi, la sécurité et les droits d’autrui. Pour cette question, la bonne réponse est « Non, ce vote est réservé aux citoyens français ».', answer: 'Non, ce vote est réservé aux citoyens français', choices: ['Non, ce vote est réservé aux citoyens français', 'Oui, automatiquement', 'Oui, après cinq ans de résidence', 'Seulement si le maire l’autorise'] },
  { category: 'Institutions', situation: true, question: 'Comment participer à la vie locale sans avoir la nationalité française ?', explanation: 'La réponse décrit le comportement attendu dans cette situation concrète, en respectant la loi, la sécurité et les droits d’autrui. Pour cette question, la bonne réponse est « S’investir dans une association ou un conseil de quartier ».', answer: 'S’investir dans une association ou un conseil de quartier', choices: ['S’investir dans une association ou un conseil de quartier', 'Voter à toutes les élections nationales', 'Devenir automatiquement maire', 'Remplacer les élus'] },
  { category: 'Institutions', situation: true, question: 'Vous avez oublié votre déclaration d’impôts. Quelle démarche entreprendre ?', explanation: 'La réponse décrit le comportement attendu dans cette situation concrète, en respectant la loi, la sécurité et les droits d’autrui. Pour cette question, la bonne réponse est « La faire rapidement, en sachant qu’une pénalité est possible ».', answer: 'La faire rapidement, en sachant qu’une pénalité est possible', choices: ['La faire rapidement, en sachant qu’une pénalité est possible', 'Ne jamais la faire', 'Attendre une convocation judiciaire', 'Changer de domicile sans prévenir'] },
  { category: 'Vie quotidienne', situation: true, question: 'Vous êtes malade et ne pouvez pas aller travailler. Que devez-vous faire ?', explanation: 'La réponse décrit le comportement attendu dans cette situation concrète, en respectant la loi, la sécurité et les droits d’autrui. Pour cette question, la bonne réponse est « Prévenir l’employeur et envoyer un arrêt de travail médical ».', answer: 'Prévenir l’employeur et envoyer un arrêt de travail médical', choices: ['Prévenir l’employeur et envoyer un arrêt de travail médical', 'Ne rien dire', 'Demander à un collègue de signer à votre place', 'Venir travailler malgré tout'] },
  { category: 'Vie quotidienne', situation: true, question: 'Lors d’un entretien, on vous demande votre orientation sexuelle. Que pouvez-vous faire ?', explanation: 'La réponse décrit le comportement attendu dans cette situation concrète, en respectant la loi, la sécurité et les droits d’autrui. Pour cette question, la bonne réponse est « Ne pas répondre, car cela relève de la vie privée ».', answer: 'Ne pas répondre, car cela relève de la vie privée', choices: ['Ne pas répondre, car cela relève de la vie privée', 'Inventer une réponse obligatoire', 'Fournir un document médical', 'Demander à votre famille de répondre'] },
  { category: 'Vie quotidienne', situation: true, question: 'Un employeur propose du travail non déclaré le week-end. Que faites-vous ?', explanation: 'La réponse décrit le comportement attendu dans cette situation concrète, en respectant la loi, la sécurité et les droits d’autrui. Pour cette question, la bonne réponse est « Refuser, car le travail dissimulé est illégal ».', answer: 'Refuser, car le travail dissimulé est illégal', choices: ['Refuser, car le travail dissimulé est illégal', 'Accepter si le salaire est élevé', 'Accepter sans prévenir personne', 'Demander à un enfant de le faire'] },
  { category: 'Vie quotidienne', situation: true, question: 'Vous refusez de recevoir les consignes d’une collègue parce que c’est une femme. Que dit la règle ?', explanation: 'La réponse décrit le comportement attendu dans cette situation concrète, en respectant la loi, la sécurité et les droits d’autrui. Pour cette question, la bonne réponse est « Le refus fondé sur le sexe est interdit ».', answer: 'Le refus fondé sur le sexe est interdit', choices: ['Le refus fondé sur le sexe est interdit', 'C’est un droit professionnel', 'Cela dépend de l’âge', 'C’est obligatoire dans certaines entreprises'] },
  { category: 'Vie quotidienne', situation: true, question: 'Vous voulez abattre un grand arbre dans votre jardin. Quelle précaution prendre ?', explanation: 'La réponse décrit le comportement attendu dans cette situation concrète, en respectant la loi, la sécurité et les droits d’autrui. Pour cette question, la bonne réponse est « Se renseigner auprès de la mairie sur les autorisations nécessaires ».', answer: 'Se renseigner auprès de la mairie sur les autorisations nécessaires', choices: ['Se renseigner auprès de la mairie sur les autorisations nécessaires', 'L’abattre sans vérifier', 'Le brûler sur place', 'Demander l’autorisation d’un voisin seulement'] },
  { category: 'Droits & devoirs', situation: true, question: 'Des parents veulent marier leur fille majeure contre sa volonté. Que dit la loi ?', explanation: 'La réponse décrit le comportement attendu dans cette situation concrète, en respectant la loi, la sécurité et les droits d’autrui. Pour cette question, la bonne réponse est « Le mariage exige le consentement libre des deux époux ».', answer: 'Le mariage exige le consentement libre des deux époux', choices: ['Le mariage exige le consentement libre des deux époux', 'Les parents peuvent toujours décider', 'Le mariage forcé est autorisé en famille', 'Le consentement n’est pas nécessaire après 18 ans'] },
  { category: 'Droits & devoirs', situation: true, question: 'Après un divorce, qui conserve en général l’autorité parentale ?', explanation: 'La réponse décrit le comportement attendu dans cette situation concrète, en respectant la loi, la sécurité et les droits d’autrui. Pour cette question, la bonne réponse est « Les deux parents conjointement ».', answer: 'Les deux parents conjointement', choices: ['Les deux parents conjointement', 'Uniquement le parent qui a le logement principal', 'Le maire', 'L’école'] },
  { category: 'Droits & devoirs', situation: true, question: 'Un parent frappe son enfant pour le punir. Est-ce autorisé ?', explanation: 'La réponse applique les règles qui protègent l’enfant, assurent la continuité de sa scolarité et organisent les échanges avec l’établissement. Pour cette question, la bonne réponse est « Non, les violences éducatives sont interdites ».', answer: 'Non, les violences éducatives sont interdites', choices: ['Non, les violences éducatives sont interdites', 'Oui, si le coup est léger', 'Oui, jusqu’à la majorité', 'Seulement avec l’accord de l’école'] },
  { category: 'Droits & devoirs', situation: true, question: 'Une jeune fille de 16 ans demande une contraception. Que peut-elle faire ?', explanation: 'La réponse décrit le comportement attendu dans cette situation concrète, en respectant la loi, la sécurité et les droits d’autrui. Pour cette question, la bonne réponse est « Y accéder gratuitement et anonymement auprès d’un professionnel ».', answer: 'Y accéder gratuitement et anonymement auprès d’un professionnel', choices: ['Y accéder gratuitement et anonymement auprès d’un professionnel', 'Obtenir une autorisation obligatoire de tous ses proches', 'Attendre sa majorité', 'Demander l’accord de son employeur'] },
  { category: 'Principes & valeurs', situation: true, question: 'À compétences égales, une femme est moins payée qu’un homme. Quel recours est possible ?', explanation: 'La réponse décrit le comportement attendu dans cette situation concrète, en respectant la loi, la sécurité et les droits d’autrui. Pour cette question, la bonne réponse est « Saisir le conseil de prud’hommes ».', answer: 'Saisir le conseil de prud’hommes', choices: ['Saisir le conseil de prud’hommes', 'Accepter car c’est légal', 'Demander à la mairie de fixer le salaire', 'Démissionner sans aucun recours'] },
  { category: 'Institutions', situation: true, question: 'Vous trouvez un portefeuille avec des papiers et de l’argent. Que devez-vous faire ?', explanation: 'La démarche indiquée permet de coopérer avec les autorités et d’utiliser la procédure prévue par la loi, sans régler le problème par soi-même. Pour cette question, la bonne réponse est « Le remettre à la police ou au service des objets trouvés ».', answer: 'Le remettre à la police ou au service des objets trouvés', choices: ['Le remettre à la police ou au service des objets trouvés', 'Garder l’argent et jeter les papiers', 'Le déposer dans une boîte aux lettres', 'Le vendre sur un site internet'] },
  { category: 'Vie quotidienne', situation: true, question: 'Vous voulez louer un logement. Que doit contenir un bail valide ?', explanation: 'La réponse décrit le comportement attendu dans cette situation concrète, en respectant la loi, la sécurité et les droits d’autrui. Pour cette question, la bonne réponse est « Un écrit signé par le propriétaire et le locataire ».', answer: 'Un écrit signé par le propriétaire et le locataire', choices: ['Un écrit signé par le propriétaire et le locataire', 'Une promesse orale uniquement', 'Une signature du voisin', 'Une autorisation de l’école'] },
];

export const questions = [...officialQuestions, ...situationalQuestions];
const categories = ['Principes & valeurs', 'Institutions', 'Droits & devoirs', 'Histoire & culture', 'Vie quotidienne'];
const shuffle = (items) => [...items].sort(() => Math.random() - 0.5);
const optionPools = [
  { pattern: /quel (?:État|pays)/i, values: ['La France', 'L’Allemagne', 'La Suisse', 'Le Royaume-Uni', 'La Norvège', 'L’Italie', 'La Belgique', 'L’Espagne'] },
  { pattern: /quelle année|en quelle année|depuis quand|de quand/i, values: ['1789', '1804', '1905', '1914', '1944', '1945', '1958', '1962', '1981', '1992', '2002'] },
  { pattern: /combien/i, values: ['12', '18', '27', '348', '577', 'Environ 35 000', 'Environ 68 millions'] },
  { pattern: /quel (?:fleuve|cours d’eau)/i, values: ['La Seine', 'La Loire', 'Le Rhône', 'La Garonne'] },
  { pattern: /quelle chaîne de montagnes/i, values: ['Les Alpes', 'Les Pyrénées', 'Les Vosges', 'Le Jura'] },
  { pattern: /quelle mer|quel océan/i, values: ['La Manche', 'La mer Méditerranée', 'L’océan Atlantique', 'La mer du Nord'] },
  { pattern: /quelle ville/i, values: ['Paris', 'Marseille', 'Lyon', 'Toulouse', 'Strasbourg', 'Bordeaux'] },
  { pattern: /quel musée/i, values: ['Le Louvre', 'Le musée d’Orsay', 'Le Centre Pompidou', 'Le musée Rodin'] },
  { pattern: /quelle cathédrale/i, values: ['Notre-Dame de Paris', 'La cathédrale de Reims', 'La cathédrale de Chartres', 'La cathédrale de Strasbourg'] },
  { pattern: /quel peintre/i, values: ['Claude Monet', 'Paul Cézanne', 'Auguste Renoir', 'Édouard Manet'] },
];
const canonicalAnswer = (item, pool) => {
  if (!pool) return item.answer;
  const source = item.answer.toLocaleLowerCase('fr-FR');
  return pool.find((choice) => {
    const normalized = choice.replace(/^(?:l['’]|le\s+|la\s+|les\s+)/i, '').toLocaleLowerCase('fr-FR');
    return source.includes(normalized);
  }) || item.answer;
};
const ignoredWords = new Set(['quel', 'quelle', 'quels', 'quelles', 'est', 'sont', 'une', 'un', 'les', 'des', 'de', 'du', 'la', 'le', 'à', 'et', 'en', 'pour', 'que', 'qui', 'dans', 'avec', 'sur', 'par', 'l', 'ce', 'cette', 'c’est']);
const keywords = (value) => new Set(value.toLocaleLowerCase('fr-FR').normalize('NFD').replace(/[\u0300-\u036f]/g, '').split(/[^a-z0-9]+/).filter((word) => word.length > 2 && !ignoredWords.has(word)));
const stripParenthetical = (value) => value.replace(/\s*\([^)]*\)/g, '').replace(/\s{2,}/g, ' ').trim();
const cleanItem = (item) => ({ ...item, answer: stripParenthetical(item.answer), choices: item.choices.map(stripParenthetical) });
const sourcesByCategory = {
  'Principes & valeurs': { label: 'Éducation nationale · Laïcité et valeurs de la République', url: 'https://www.education.gouv.fr/la-laicite-l-ecole-12482' },
  Institutions: { label: 'Vie-publique · Les institutions de la République', url: 'https://www.vie-publique.fr/fiches/23911-les-institutions-de-la-republique' },
  'Droits & devoirs': { label: 'Service-Public · Citoyenneté et démarches', url: 'https://www.service-public.fr/particuliers/vosdroits/N47' },
  'Histoire & culture': { label: 'Éduscol · Ressources éducatives', url: 'https://eduscol.education.fr/' },
  'Vie quotidienne': { label: 'Service-Public · Portail officiel', url: 'https://www.service-public.fr/' },
};
const explanationDetail = (item) => {
  const q = item.question.toLocaleLowerCase('fr-FR');
  if (/année|date|depuis quand|de quand/.test(q)) return 'Cette date constitue le repère chronologique attendu pour situer cet événement dans l’histoire civique française ou européenne.';
  if (/qui dirige|qui nomme|qui est le|quel est le rôle|mission/.test(q)) return 'Cette réponse identifie précisément l’autorité compétente et permet de distinguer son rôle de celui des autres institutions.';
  if (/laïcité|religion|religieux|conscience|culte/.test(q)) return 'Cette règle garantit la liberté de conscience et l’égalité, tout en imposant la neutralité aux services et agents publics concernés.';
  if (/vote|élection|électoral|citoyen/.test(q)) return 'Cette règle précise les conditions concrètes de la participation civique et distingue un droit, une condition d’exercice ou une obligation.';
  if (/liberté|droit|obligation|interdit|loi|peine|infraction|crime|délit/.test(q)) return 'Cette réponse applique le principe juridique demandé : les libertés sont protégées, mais leur exercice s’inscrit dans le respect de la loi et des droits d’autrui.';
  if (/où|quelle ville|quel pays|frontière|mer|fleuve|montagne|région|territoire/.test(q)) return 'Ce repère permet de situer correctement le territoire, les institutions ou le patrimoine concernés.';
  if (/école|enfant|parent|travail|emploi|santé|médecin|logement|naissance|mariage|urgence|police/.test(q)) return 'Cette réponse indique la conduite ou la démarche attendue dans la vie quotidienne, ainsi que le service ou le principe à respecter.';
  if (/pourquoi|à quoi sert|que signifie|qu’est-ce que|qu'est-ce que|que représente/.test(q)) return 'La réponse donne la définition ou la fonction précise demandée par la question, sans l’étendre à une autre notion.';
  return 'Cette réponse correspond précisément au sujet et au terme recherché dans la question.';
};
const explanationFor = (item) => {
  const source = sourcesByCategory[item.category] || sourcesByCategory['Vie quotidienne'];
  if (item.explanation) {
    const text = typeof item.explanation === 'string' && !item.explanation.includes(item.question)
      ? `${item.explanation} Question concernée : « ${item.question} ».`
      : item.explanation;
    return typeof item.explanation === 'string'
      ? { text, sourceLabel: source.label, sourceUrl: source.url }
      : item.explanation;
  }
  const prefix = item.situation
    ? 'Dans cette situation, il faut appliquer la règle indiquée et effectuer la démarche attendue, sans se faire justice soi-même.'
    : explanationDetail(item);
  return {
    text: `${prefix} Pour « ${item.question} », la réponse correcte est « ${item.answer} ».`,
    sourceLabel: source.label,
    sourceUrl: source.url,
  };
};
const relatedDistractors = (item) => {
  const sourceWords = keywords(`${item.question} ${item.answer}`);
  return officialQuestions
    .filter((candidate) => candidate.category === item.category && candidate.question !== item.question && candidate.answer !== item.answer)
    .map((candidate) => {
      const candidateWords = keywords(`${candidate.question} ${candidate.answer}`);
      const overlap = [...sourceWords].filter((word) => candidateWords.has(word)).length;
      return { answer: candidate.answer, score: overlap };
    })
    .sort((a, b) => b.score - a.score)
    .map(({ answer }) => stripParenthetical(answer))
    .filter((answer, index, values) => values.indexOf(answer) === index)
    .slice(0, 3);
};
export const buildChoices = (item) => {
  const cleaned = cleanItem(item);
  if (cleaned.precise) return shuffle(cleaned.choices);
  const pool = optionPools.find(({ pattern }) => pattern.test(cleaned.question))?.values;
  const answer = canonicalAnswer(cleaned, pool);
  const distractors = pool
    ? pool.filter((choice) => choice !== answer)
    : cleaned.situation
      ? cleaned.choices.filter((choice) => choice !== cleaned.answer)
      : relatedDistractors(cleaned);
  return shuffle([answer, ...shuffle(distractors).slice(0, 3)]);
};
export const buildQuiz = ({ category, situationsOnly = false } = {}) => {
  if (situationsOnly) {
    return shuffle(situationalQuestions.filter((item) => item.situation)).slice(0, 20).map((item) => {
      const cleaned = cleanItem(item);
      return { ...cleaned, explanation: explanationFor(cleaned), choices: buildChoices(cleaned) };
    });
  }
  if (category) {
    return shuffle(officialQuestions.filter((item) => item.category === category)).slice(0, 20).map((item) => {
      const cleaned = cleanItem(item);
      return { ...cleaned, explanation: explanationFor(cleaned), choices: buildChoices(cleaned) };
    });
  }
  const distribution = [6, 6, 6, 5, 5];
  const official = categories.flatMap((category, index) => shuffle(officialQuestions.filter((item) => item.category === category)).slice(0, distribution[index]));
  const situations = shuffle(situationalQuestions.filter((item) => item.situation)).slice(0, 12);
  return shuffle([...official, ...situations]).map((item) => {
    const cleaned = cleanItem(item);
    const pool = optionPools.find(({ pattern }) => pattern.test(cleaned.question))?.values;
    const answer = cleaned.precise ? cleaned.answer : canonicalAnswer(cleaned, pool);
    return { ...cleaned, answer, explanation: explanationFor({ ...cleaned, answer }), choices: buildChoices({ ...cleaned, answer }) };
  });
};

function App() {
  const [screen, setScreen] = useState('home');
  const [requestedSize] = useState(40);
  const [quizCategory, setQuizCategory] = useState('');
  const [quizQuestions, setQuizQuestions] = useState([]);
  const [current, setCurrent] = useState(0);
  const [selected, setSelected] = useState(null);
  const [score, setScore] = useState(0);
  const [answers, setAnswers] = useState([]);

  const startQuiz = (category = quizCategory) => {
    setQuizQuestions(buildQuiz(category === '__situations__' ? { situationsOnly: true } : category ? { category } : {}));
    setCurrent(0);
    setSelected(null);
    setScore(0);
    setAnswers([]);
    setScreen('quiz');
  };

  const question = quizQuestions[current];
  const progress = quizQuestions.length ? ((current + (selected !== null ? 1 : 0)) / quizQuestions.length) * 100 : 0;

  const choose = (choice) => {
    if (selected !== null) return;
    setSelected(choice);
    const correct = choice === question.answer;
    if (correct) setScore((value) => value + 1);
    setAnswers((items) => [...items, { question: question.question, choice, correct }]);
  };

  const next = () => {
    if (current === quizQuestions.length - 1) setScreen('results');
    else {
      setCurrent((value) => value + 1);
      setSelected(null);
    }
  };

  useEffect(() => {
    const onKey = (event) => {
      if (screen !== 'quiz' || !question) return;
          if (selected !== null && (event.key === 'Enter' || event.key === ' ')) {
        event.preventDefault();
        next();
      }
      const number = Number(event.key);
      if (number >= 1 && number <= 4) choose(question.choices[number - 1]);
    };
    window.addEventListener('keydown', onKey);
    return () => window.removeEventListener('keydown', onKey);
  }, [screen, question, selected, current]);

  if (screen === 'quiz' && question) return <QuizScreen question={question} current={current} total={quizQuestions.length} progress={progress} selected={selected} choose={choose} next={next} />;
  if (screen === 'results') return <Results score={score} total={quizQuestions.length} answers={answers} restart={() => startQuiz(quizCategory)} home={() => setScreen('home')} />;
  return <Home quizCategory={quizCategory} setQuizCategory={setQuizCategory} startQuiz={startQuiz} />;
}

function Shell({ children }) {
  return <main className="app-shell"><header className="topbar"><div className="brand"><span className="brand-mark">RF</span><span>Révise citoyen</span></div><span className="source-label">Carte de résident · 2025</span></header>{children}<footer>Un outil de révision local · Les réponses proviennent du support officiel fourni</footer></main>;
}

function Home({ quizCategory, setQuizCategory, startQuiz }) {
  const categories = ['Principes & valeurs', 'Institutions', 'Droits & devoirs', 'Histoire & culture', 'Vie quotidienne'];
  return <Shell><section className="hero home-card"><div className="eyebrow"><Sparkles size={16} /> Préparez-vous sereinement</div><h1>L’examen civique,<br /><em>à votre rythme.</em></h1><p className="lead">Révisez les questions officielles et entraînez-vous avec des situations concrètes de la vie quotidienne.</p><div className="home-stats"><div><strong>209</strong><span>questions officielles</span></div><div><strong>50</strong><span>mises en situation</span></div><div><strong>4</strong><span>choix par question</span></div></div><div className="setup"><div><label>Quiz complet</label><p>28 questions officielles + 12 mises en situation.</p></div><button className="size-option active" onClick={() => { setQuizCategory(''); startQuiz(''); }}>40<small>questions</small></button></div><div className="theme-setup"><div><label>Révision par thème</label><p>20 questions officielles, sans mise en situation.</p></div><select value={quizCategory.startsWith('__') ? '' : quizCategory} onChange={(event) => setQuizCategory(event.target.value)} aria-label="Choisir un thème"><option value="">Choisir un thème</option>{categories.map((category) => <option key={category} value={category}>{category}</option>)}</select><button className="secondary-button" disabled={!quizCategory || quizCategory === '__situations__'} onClick={() => startQuiz(quizCategory)}>Démarrer ce thème <ArrowRight size={16} /></button></div><div className="theme-setup situation-setup"><div><label>Mise en situation</label><p>20 situations concrètes pour vous entraîner à réagir.</p></div><button className="secondary-button" onClick={() => { setQuizCategory('__situations__'); startQuiz('__situations__'); }}>S’entraîner aux situations <ArrowRight size={16} /></button></div><p className="keyboard-hint"><CircleHelp size={15} /> Répondez aussi avec les touches 1 à 4</p></section></Shell>;
}

function QuizScreen({ question, current, total, progress, selected, choose, next }) {
  const isCorrect = selected === question.answer;
  return <Shell><section className="quiz-wrap"><div className="quiz-meta"><button className="back-button" onClick={() => window.location.reload()}><ChevronLeft size={18} /> Quitter</button><span className="question-count">Question <strong>{String(current + 1).padStart(2, '0')}</strong> / {total}</span></div><div className="progress-track"><span style={{ width: `${progress}%` }} /></div><div className="category-pill">{question.category}</div><article className="question-card"><div className="question-icon"><Flag size={21} /></div><h2>{question.question}</h2><p className="instruction">Sélectionnez la bonne réponse</p><div className="answers">{question.choices.map((choice, index) => { const state = selected === null ? '' : choice === question.answer ? 'correct' : choice === selected ? 'wrong' : 'muted'; return <button key={choice} className={`answer ${state}`} onClick={() => choose(choice)} aria-pressed={selected === choice}><span className="answer-key">{index + 1}</span><span>{choice}</span>{selected !== null && choice === question.answer && <Check className="answer-icon" size={19} />}{selected === choice && choice !== question.answer && <X className="answer-icon" size={19} />}</button>; })}</div>{selected !== null && <div className={`feedback ${isCorrect ? 'feedback-good' : 'feedback-bad'}`}><div className="feedback-icon">{isCorrect ? <Check size={18} /> : <X size={18} />}</div><div><strong>{isCorrect ? 'Bonne réponse !' : 'Pas tout à fait.'}</strong><span>{isCorrect ? 'Continuez comme ça.' : `La bonne réponse est : ${question.answer}`}</span><p className="explanation"><strong>Pourquoi ?</strong> {question.explanation.text}<a href={question.explanation.sourceUrl} target="_blank" rel="noreferrer">Source officielle : {question.explanation.sourceLabel}</a></p></div></div>}<div className="question-footer"><span><Clock3 size={15} /> Pas de limite de temps</span>{selected !== null && <button className="primary-button compact" onClick={next}>{current === total - 1 ? 'Voir mon score' : 'Question suivante'} <ArrowRight size={17} /></button>}</div></article></section></Shell>;
}

function Results({ score, total, answers, restart, home }) {
  const percentage = Math.round((score / total) * 100);
  const message = percentage >= 80 ? 'Excellent travail !' : percentage >= 60 ? 'Bonne base, continuez vos révisions.' : 'Chaque erreur est une occasion d’apprendre.';
  return <Shell><section className="results-card"><div className="result-icon"><Award size={32} /></div><div className="eyebrow">Quiz terminé</div><h1>{message}</h1><p className="lead">Voici votre résultat sur cette session.</p><div className="score-ring" style={{ '--score': `${percentage * 3.6}deg` }}><div><strong>{score}<small>/{total}</small></strong><span>bonnes réponses</span></div></div><div className="result-summary"><span>Votre score</span><strong>{percentage}%</strong></div><div className="result-actions"><button className="primary-button" onClick={restart}><RotateCcw size={18} /> Recommencer</button><button className="secondary-button" onClick={home}>Retour à l’accueil</button></div><details className="review"><summary>Revoir mes réponses</summary><div>{answers.map((item, index) => <div className="review-item" key={`${item.question}-${index}`}><span className={item.correct ? 'review-check' : 'review-cross'}>{item.correct ? <Check size={13} /> : <X size={13} />}</span><p>{item.question}<small>{item.correct ? item.choice : `Votre réponse : ${item.choice}`}</small></p></div>)}</div></details></section></Shell>;
}

if (typeof document !== 'undefined') {
  createRoot(document.getElementById('root')).render(<App />);
}
